-- [MIGRATION] Resilient KDK Synchronization RPCs (v1.7)
-- This migration ensures the database can handle both bulk syncs and atomic status updates.

-- 1. Ensure matches table uses TEXT for ID (to support frontend-generated deterministic IDs)
DO $$ 
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'matches' 
        AND column_name = 'id' 
        AND data_type = 'uuid'
    ) THEN
        ALTER TABLE public.matches ALTER COLUMN id TYPE TEXT;
    END IF;
END $$;

-- 2. RPC: sync_tournament_matches
-- Handles bulk upsert of matches generated by the frontend engine.
CREATE OR REPLACE FUNCTION public.sync_tournament_matches(p_matches JSONB)
RETURNS VOID AS $$
BEGIN
    INSERT INTO public.matches (
        id, club_id, session_id, session_title, round, court, 
        player_ids, player_names, score1, score2, status, mode, group_name
    )
    SELECT 
        (m->>'id')::TEXT,
        (m->>'club_id')::TEXT,
        (m->>'session_id')::TEXT,
        (m->>'session_title')::TEXT,
        (m->>'round')::INTEGER,
        (m->>'court')::INTEGER,
        -- Handle both playerIds (frontend) and player_ids (db) naming
        ARRAY(SELECT jsonb_array_elements_text(COALESCE(m->'playerIds', m->'player_ids'))),
        ARRAY(SELECT jsonb_array_elements_text(m->'player_names')),
        COALESCE((m->>'score1')::INTEGER, 0),
        COALESCE((m->>'score2')::INTEGER, 0),
        COALESCE((m->>'status')::TEXT, 'waiting'),
        COALESCE((m->>'mode')::TEXT, 'KDK'),
        COALESCE(m->>'groupName', m->>'group_name')
    FROM JSONB_ARRAY_ELEMENTS(p_matches) AS m
    ON CONFLICT (id) DO UPDATE SET
        status = EXCLUDED.status,
        court = EXCLUDED.court,
        score1 = EXCLUDED.score1,
        score2 = EXCLUDED.score2,
        player_names = EXCLUDED.player_names,
        player_ids = EXCLUDED.player_ids,
        group_name = EXCLUDED.group_name;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. RPC: update_match_status
-- Handles atomic updates for starting, canceling, or finishing a match.
CREATE OR REPLACE FUNCTION public.update_match_status(
    p_match_id TEXT,
    p_status TEXT,
    p_court INTEGER DEFAULT NULL,
    p_score1 INTEGER DEFAULT NULL,
    p_score2 INTEGER DEFAULT NULL
)
RETURNS VOID AS $$
BEGIN
    UPDATE public.matches
    SET 
        status = p_status,
        court = CASE WHEN p_court IS NOT NULL THEN p_court ELSE court END,
        score1 = CASE WHEN p_score1 IS NOT NULL THEN p_score1 ELSE score1 END,
        score2 = CASE WHEN p_score2 IS NOT NULL THEN p_score2 ELSE score2 END
    WHERE id = p_match_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Grant Permissions
GRANT EXECUTE ON FUNCTION public.sync_tournament_matches(JSONB) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.update_match_status(TEXT, TEXT, INTEGER, INTEGER, INTEGER) TO anon, authenticated, service_role;

-- 5. Helper: date_match_status (Prevent 404 from old code if lingering)
-- Note: This is a "ghost" function to capture and redirect any legacy v1.5 requests.
CREATE OR REPLACE FUNCTION public.date_match_status(match_id TEXT)
RETURNS SETOF public.matches AS $$
BEGIN
    RETURN QUERY SELECT * FROM public.matches WHERE id = match_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
GRANT EXECUTE ON FUNCTION public.date_match_status(TEXT) TO anon, authenticated, service_role;
