import { createStitches } from '@stitches/react';

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      black: '#000000',
      white: '#ffffff',
      gold: '#D4AF37',
      goldLight: '#F3E5AB',
      goldGlint: '#FFD700', // Electric Yellow/Gold
      goldMuted: 'rgba(212, 175, 55, 0.15)',
      goldGlass: 'rgba(212, 175, 55, 0.03)',
      carbon: '#0A0A0A',
      gray950: '#050505',
      gray900: '#0A0A0A',
      gray850: '#151515',
      gray800: '#1E1E1E',
      gray700: '#2A2A2A',
      accent: '$gold',
      success: '#4CAF50',
      error: '#FF4B2B',
      deepNavy: '#0F172A',
      cardNavy: '#1E293B',
    },
    space: {
      1: '2px',
      2: '4px',
      3: '8px',
      4: '12px',
      5: '16px',
      6: '24px',
      8: '32px',
      10: '40px',
      12: '48px',
    },
    fontSizes: {
      xs: '10px',
      sm: '12px',
      base: '14px',
      lg: '16px',
      xl: '18px',
      '2xl': '24px',
      '3xl': '32px',
      '4xl': '48px',
      '5xl': '64px',
    },
    fonts: {
      sans: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      sporty: 'var(--font-rajdhani), sans-serif',
      display: 'var(--font-orbitron), sans-serif',
      mono: 'Menlo, Monaco, Consolas, "Courier New", monospace',
    },
    fontWeights: {
      light: 300,
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      black: 900,
    },
    lineHeights: {
      none: 1,
      tight: 1.1,
      snug: 1.375,
      normal: 1.5,
      relaxed: 1.625,
      loose: 2,
    },
    letterSpacings: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
      mega: '0.4em',
    },
    radii: {
      sm: '4px',
      md: '8px',
      lg: '16px',
      xl: '24px',
      '2xl': '40px',
      full: '9999px',
    },
    shadows: {
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      gold: '0 0 15px rgba(212, 175, 55, 0.3)',
      goldGlow: '0 0 30px rgba(212, 175, 55, 0.5)',
      goldAura: '0 0 50px rgba(212, 175, 55, 0.2)',
      glass: 'inset 0 0 20px rgba(255, 255, 255, 0.02), 0 15px 35px rgba(0, 0, 0, 0.9)',
      volumetric: 'inset 0 2px 4px rgba(255, 255, 255, 0.04), 0 10px 20px rgba(0, 0, 0, 0.8)',
      inner: 'inset 0 2px 10px rgba(0, 0, 0, 0.8)',
    },
    gradients: {
      blackGold: 'linear-gradient(135deg, $gray900, $black)',
      diagonal: 'linear-gradient(135deg, rgba(25, 25, 25, 1) 0%, rgba(5, 5, 5, 1) 100%)',
      carbon: 'linear-gradient(135deg, #0A0A0A 0%, #000000 100%)',
      shimmer: 'linear-gradient(90deg, transparent, rgba(255, 215, 0, 0.1), transparent)',
    },
    zIndices: {
      hide: -1,
      auto: 'auto',
      base: 0,
      docked: 10,
      dropdown: 1000,
      sticky: 1100,
      banner: 1200,
      overlay: 1300,
      modal: 1400,
      popover: 1500,
      skipLink: 1600,
      toast: 1700,
      tooltip: 1800,
    },
  },
  media: {
    mobile: '(max-width: 640px)',
    tablet: '(max-width: 1024px)',
    desktop: '(min-width: 1025px)',
    fold: '(max-width: 280px)',
  },
  utils: {
    p: (value: any) => ({ padding: value }),
    pt: (value: any) => ({ paddingTop: value }),
    pr: (value: any) => ({ paddingRight: value }),
    pb: (value: any) => ({ paddingBottom: value }),
    pl: (value: any) => ({ paddingLeft: value }),
    px: (value: any) => ({ paddingLeft: value, paddingRight: value }),
    py: (value: any) => ({ paddingTop: value, paddingBottom: value }),

    m: (value: any) => ({ margin: value }),
    mt: (value: any) => ({ marginTop: value }),
    mr: (value: any) => ({ marginRight: value }),
    mb: (value: any) => ({ marginBottom: value }),
    ml: (value: any) => ({ marginLeft: value }),
    mx: (value: any) => ({ marginLeft: value, marginRight: value }),
    my: (value: any) => ({ marginTop: value, marginBottom: value }),

    bg: (value: any) => ({ backgroundColor: value }),
    br: (value: any) => ({ borderRadius: value }),
    
    size: (value: any) => ({ width: value, height: value }),
    
    borderGlow: (value: any) => ({
      border: `1px solid ${value || 'rgba(212, 175, 55, 0.3)'}`,
      filter: `drop-shadow(0 0 2px ${value || 'rgba(212, 175, 55, 0.4)'})`,
    }),
    
    volumetricBox: () => ({
      background: 'linear-gradient(135deg, #151515 0%, #050505 100%)',
      boxShadow: 'inset 0 1px 1px rgba(255,255,255,0.05), 0 10px 20px rgba(0,0,0,0.8)',
      border: '1px solid rgba(212, 175, 55, 0.15)',
    }),
  },
});

export const globalStyles = globalCss({
  '*': { margin: 0, padding: 0, boxSizing: 'border-box' },
  'html, body': {
    backgroundColor: '$black',
    color: '$white',
    fontFamily: '$sporty', // High-fidelity sporty font by default
    overflowX: 'hidden',
    height: '100%',
    '-webkit-font-smoothing': 'antialiased',
  },
  'a': {
    color: 'inherit',
    textDecoration: 'none',
  },
  'button': {
    cursor: 'pointer',
    border: 'none',
    outline: 'none',
    background: 'none',
    fontFamily: 'inherit',
  },
  '::-webkit-scrollbar': {
    width: '4px',
  },
  '::-webkit-scrollbar-track': {
    background: '$black',
  },
  '::-webkit-scrollbar-thumb': {
    background: '$gray700',
    borderRadius: '$full',
  },
});
